services:
  - type: web
    name: my-wa-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.puppeteer-cache
      - key: PORT
        generateValue: false
      - key: ADMIN_PASS
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_BRANCH
        value: main
    disk:
      name: bot-data
      mountPath: /opt/render/project/src
      sizeGB: 1
